### PR TITLE
Jin

### PR DESCRIPTION
**Pull request by leepc12**
Modifications for

prog. report
no sort for help
all shell cmds shown
long task hint
chkpoint disabled
task graph disabled

### CODE REVIEW

**Comment by pcingola** [comment]
Awesome thank you!

**Comment by pcingola** [comment]
Overall the PR looks good and I'll start merging each item (hopefully tomorrow).
Thank you again for contributing your ideas and your code!

**Comment by leepc12** [comment]
I found that checkpoints are still being generated even though it's already disabled in bds.config.

```
sge.pe = shm
sge.mem = h_vmem
sge.timeout = h_rt
taskShell = /bin/bash -e
sysShell = /bin/bash -e -c
pidRegex = "Your job (\\S+)"

# checkpoint disabled
disableCheckpoint = true

# to show full commands on task
taskMaxHintLen = 50000

# filter out commands including "modules.sh" from task hint due to initialization command like (. /etc/profile.d/modules.sh)
filterOutTaskHint = modules.sh

# to show full stderr/stdout results on report
tailLines = 100000000

# Use -V to pass all env. vars to qsub jobs (not recommended)
#clusterRunAdditionalArgs = -V

# If BDS is locally installed on your home $HOME/.bds/ should be included in your PATH
# Do not use $HOME in the following line. Specify absolute path of your home + /.bds

#clusterRunAdditionalArgs = -v PATH=/home/leepc12/.bds
#clusterRunAdditionalArgs = -v PATH=/home/leepc12/.bds -A accountID -M user@gmail.com
```

**Comment by pcingola** [comment]
OK, thank you for reporting this. I'll fix it.

**Comment by pcingola** [comment]
Fixed.

**Pull request closed without merging**
